      - uses: mfinelli/setup-imagemagick@v1        
      - name: Process all files
        run: |
          mogrify -resize 720x720\> -format jpg -path static/images/ images/*.png
          mogrify -resize 720x720\> -path static/images/ images/*.jpg
          mogrify -resize 720x720\> -path static/images/ images/*.gif
